### ISSUE TITLE
Bug: "Sign in with GitHub to use Deploy to GitHub pages" appears in Accounts tab despite signing in 

### ISSUE THREAD

**Issue by deepindersinghbti** [blackgirlbytes/vscodeextension-deploy-to-gh-pages#4]
### Describe the bug

I am already signed in to VS Code using  my GitHub account, but the "Sign in with GitHub to use Deploy to GitHub pages" error is still there in the **Accounts** tab
![Screenshot (17)](https://user-images.githubusercontent.com/85491004/166102681-7953c0cd-fcda-40f6-a540-c74dc7b8c9dc.png)
.

### Steps to reproduce

1. Click the Accounts button on the Primary Side Bar
2. Click **Sign in with GitHub to use Deploy to GitHub Pages**
3. Browser opens automatically and asks for permission to open VS Code.
4. VS Code shows a pop-up, "Allow an extension to open this URL?", Select **Yes**
5. No change is observed, and we just see a notification in the **Accounts** tab which says, "Sign in with GitHub to use Deploy to GitHub pages"

### Affected services

opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Testing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blackgirlbytes** [comment]
@deepindersinghbti how come you closed this? is this already fixed for you? I hadn't gotten a chance to touch this because I'm on vacation

**Comment by deepindersinghbti** [comment]
Yes, I closed this issue because when I checked my editor yesterday and tried to use this extension, the notification was no longer popping up! I didn't understand why. Later, when I tried to use this extension, it worked like a charm! Thank you very much for developing and maintaining such an awesome extension. It made my coding so much faster!

**Comment by blackgirlbytes** [comment]
oh that's amazing to hear! Thank you @deepindersinghbti
